# Generated by Django 4.2.7 on 2025-06-15 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul Acara")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Deskripsi Acara"),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="Waktu Mulai")),
                ("end_datetime", models.DateTimeField(verbose_name="Waktu Selesai")),
                (
                    "participants",
                    models.PositiveIntegerField(verbose_name="Jumlah Peserta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("cancelled", "Dibatalkan"),
                            ("completed", "Selesai"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Persetujuan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Disetujui Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pemesanan",
                "verbose_name_plural": "Pemesanan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama Ruangan")),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                ("capacity", models.PositiveIntegerField(verbose_name="Kapasitas")),
                ("location", models.CharField(max_length=200, verbose_name="Lokasi")),
                ("facilities", models.TextField(blank=True, verbose_name="Fasilitas")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="rooms/", verbose_name="Gambar"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ruangan",
                "verbose_name_plural": "Ruangan",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="Status Lama"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="Status Baru"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="rooms.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diubah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riwayat Booking",
                "verbose_name_plural": "Riwayat Booking",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.room",
                verbose_name="Ruangan",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pengguna",
            ),
        ),
    ]
