version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: room_usage_db
    restart: always
    environment:
      MYSQL_DATABASE: room_usage_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    container_name: room_usage_web
    command: ./docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=room_usage_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password

volumes:
  mysql_data:
